# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Douban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10, verbose_name='评论人')),
                ('star', models.IntegerField(choices=[(1, '很差'), (2, '较差'), (3, '还行'), (4, '推荐'), (5, '力荐')], verbose_name='星数')),
                ('comments', models.CharField(max_length=128, verbose_name='评论')),
            ],
            options={
                'verbose_name': '影评信息',
                'verbose_name_plural': '影评信息',
            },
        ),
    ]
